apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  namespace: node1
  name: node-test
spec:
  selector:
    name: node-test
  replicas: 3
  template:
    metadata:
      labels:
        name: node-test
    spec:
      containers:
        - name: container
          image: >-
            docker.io/kartikeyavashishtha/test123@sha256:b7f0b169cd087d933e9eb390ef699ee46f770e14638126f7ac1f87414ff87037
          ports:
            - containerPort: 3000
              protocol: TCP
          env: []
      imagePullSecrets:
        - name: docker-credentials
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 600
      updatePeriodSeconds: 1
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - container
        from:
          kind: ImageStreamTag
          name: 'test123:latest'
          namespace: node1
    - type: ConfigChange
  paused: false
